"""
Algorithms Package

This package provides foundational algorithm definitions for the Quantum package.

Purpose
-------
Provide comprehensive foundational definitions for quantum computing operations.

Modules
-------
- exceptions: Quantum exception hierarchy
- enums: Quantum enumerations
- types: Quantum type definitions
- interfaces: Quantum interface definitions
- protocols: Quantum protocol definitions
- constants: Quantum constants
- factories: Quantum factory definitions
- serializers: Quantum serializer definitions
- validators: Quantum validator definitions
"""

from __future__ import annotations

from quantsmind.quantum.algorithms.constants import (
    BACKEND_MATRIX_PRODUCT_STATE,
    BACKEND_NOISY,
    BACKEND_STATEVECTOR,
    BACKEND_UNITARY,
    DEFAULT_BACKEND_TIMEOUT,
    DEFAULT_CIRCUIT_DEPTH,
    DEFAULT_CONVERGENCE_TOLERANCE,
    DEFAULT_ERROR_RATE,
    DEFAULT_GATE_COUNT,
    DEFAULT_LEARNING_RATE,
    DEFAULT_MAX_ITERATIONS,
    DEFAULT_MEASUREMENT_BASIS,
    DEFAULT_MEASUREMENT_TYPE,
    DEFAULT_NOISE_MODEL,
    DEFAULT_NUM_QUBITS,
    DEFAULT_NUM_SHOTS,
    DEFAULT_OPTIMIZATION_LEVEL,
    DEFAULT_OPTIMIZATION_TARGET,
    DEFAULT_PROVIDER_NAME,
    DEFAULT_SERIALIZATION_FORMAT,
    DEFAULT_SIMULATOR_NAME,
    DEFAULT_T1,
    DEFAULT_T2,
    DEFAULT_TRANSPILATION_TARGET,
    GATE_BARRIER,
    GATE_CCX,
    GATE_CX,
    GATE_CY,
    GATE_CZ,
    GATE_H,
    GATE_IDENTITY,
    GATE_ISWAP,
    GATE_MEASURE,
    GATE_PHASE,
    GATE_RESET,
    GATE_RX,
    GATE_RY,
    GATE_RZ,
    GATE_S,
    GATE_SWAP,
    GATE_SX,
    GATE_T,
    GATE_U,
    GATE_X,
    GATE_Y,
    GATE_Z,
    H_BAR,
    HADAMARD_MATRIX,
    IDENTITY_MATRIX,
    MAX_GATE_COUNT,
    MAX_QUBITS,
    MAX_SHOTS,
    MIN_GATE_COUNT,
    MIN_QUBITS,
    MIN_SHOTS,
    MINUS_STATE,
    ONE_STATE,
    PAULI_X_MATRIX,
    PAULI_Y_MATRIX,
    PAULI_Z_MATRIX,
    PI,
    PI_2,
    PI_4,
    PLANCK_CONSTANT,
    PLUS_STATE,
    PROVIDER_AWS_BRAKET,
    PROVIDER_AZURE_QUANTUM,
    PROVIDER_GOOGLE,
    PROVIDER_IBM,
    PROVIDER_IONQ,
    PROVIDER_LOCAL,
    PROVIDER_QUANTINUUM,
    PROVIDER_RIGETTI,
    PROVIDER_XANADU,
    QUANTUM_SDK_VERSION,
    S_GATE_MATRIX,
    SINGLE_QUBIT_GATES,
    SQRT_2,
    SQRT_2_INV,
    SUPPORTED_SERIALIZATION_FORMATS,
    SX_GATE_MATRIX,
    T_GATE_MATRIX,
    THREE_QUBIT_GATES,
    TWO_QUBIT_GATES,
    ZERO_STATE,
)
from quantsmind.quantum.algorithms.enums import (
    AlgorithmType,
    BackendType,
    BasisType,
    CompilerPassType,
    GateType,
    JobStatus,
    MeasurementType,
    NoiseType,
    OptimizationLevel,
    PauliType,
    ProviderType,
    QubitState,
    StateType,
    TranspilerTarget,
)
from quantsmind.quantum.algorithms.exceptions import (
    AlgorithmError,
    BackendError,
    CircuitError,
    CompilerError,
    ExecutionError,
    GateError,
    MeasurementError,
    NoiseError,
    ParameterError,
    ProviderError,
    QuantumError,
    QubitError,
    SerializationError,
    StateError,
    ValidationError,
)
from quantsmind.quantum.algorithms.factories import (
    BackendFactory,
    GateFactory,
    QuantumFactory,
    StateFactory,
)
from quantsmind.quantum.algorithms.interfaces import (
    IMeasurement,
    IQuantumBackend,
    IQuantumCircuit,
    IQuantumCompiler,
    IQuantumGate,
    IQuantumJob,
    IQuantumProvider,
    IQuantumState,
    IQubit,
)
from quantsmind.quantum.algorithms.protocols import (
    MeasurementProtocol,
    QuantumBackendProtocol,
    QuantumCircuitProtocol,
    QuantumCompilerProtocol,
    QuantumGateProtocol,
    QuantumJobProtocol,
    QuantumProviderProtocol,
    QuantumStateProtocol,
    QubitProtocol,
)
from quantsmind.quantum.algorithms.serializers import (
    CircuitSerializer,
    GateSerializer,
    QuantumSerializer,
    StateSerializer,
)
from quantsmind.quantum.algorithms.types import (
    BackendConfig,
    CircuitDepth,
    CompilerConfig,
    CompilerPass,
    ComplexMatrix,
    DensityMatrix,
    ExecutionResult,
    GateCount,
    GateFunction,
    GateParameters,
    JobResult,
    MeasurementBasis,
    MeasurementFunction,
    MeasurementResult,
    NoiseConfig,
    OptimizationFunction,
    ProbabilityDistribution,
    ProviderConfig,
    QuantumOperator,
    QuantumState,
    QubitCount,
    QubitIndex,
    QubitIndices,
    StateVector,
    ValidationResult,
)
from quantsmind.quantum.algorithms.validators import (
    CircuitValidator,
    GateValidator,
    MeasurementValidator,
    QuantumValidator,
    StateValidator,
)

__all__ = [
    # Constants
    "QUANTUM_SDK_VERSION",
    "H_BAR",
    "PLANCK_CONSTANT",
    "BOLTZMANN_CONSTANT",
    "SQRT_2",
    "SQRT_2_INV",
    "PI",
    "PI_2",
    "PI_4",
    "IDENTITY_MATRIX",
    "PAULI_X_MATRIX",
    "PAULI_Y_MATRIX",
    "PAULI_Z_MATRIX",
    "HADAMARD_MATRIX",
    "S_GATE_MATRIX",
    "T_GATE_MATRIX",
    "SX_GATE_MATRIX",
    "ZERO_STATE",
    "ONE_STATE",
    "PLUS_STATE",
    "MINUS_STATE",
    "DEFAULT_NUM_QUBITS",
    "DEFAULT_NUM_SHOTS",
    "DEFAULT_OPTIMIZATION_LEVEL",
    "DEFAULT_CIRCUIT_DEPTH",
    "DEFAULT_GATE_COUNT",
    "DEFAULT_SIMULATOR_NAME",
    "DEFAULT_PROVIDER_NAME",
    "DEFAULT_BACKEND_TIMEOUT",
    "DEFAULT_TRANSPILATION_TARGET",
    "DEFAULT_OPTIMIZATION_TARGET",
    "DEFAULT_MEASUREMENT_BASIS",
    "DEFAULT_MEASUREMENT_TYPE",
    "DEFAULT_NOISE_MODEL",
    "DEFAULT_ERROR_RATE",
    "DEFAULT_T1",
    "DEFAULT_T2",
    "DEFAULT_MAX_ITERATIONS",
    "DEFAULT_CONVERGENCE_TOLERANCE",
    "DEFAULT_LEARNING_RATE",
    "DEFAULT_SERIALIZATION_FORMAT",
    "SUPPORTED_SERIALIZATION_FORMATS",
    "MIN_QUBITS",
    "MAX_QUBITS",
    "MIN_SHOTS",
    "MAX_SHOTS",
    "MIN_GATE_COUNT",
    "MAX_GATE_COUNT",
    "GATE_IDENTITY",
    "GATE_X",
    "GATE_Y",
    "GATE_Z",
    "GATE_H",
    "GATE_S",
    "GATE_T",
    "GATE_SX",
    "GATE_RX",
    "GATE_RY",
    "GATE_RZ",
    "GATE_PHASE",
    "GATE_U",
    "GATE_CX",
    "GATE_CY",
    "GATE_CZ",
    "GATE_SWAP",
    "GATE_ISWAP",
    "GATE_CCX",
    "GATE_MEASURE",
    "GATE_RESET",
    "GATE_BARRIER",
    "SINGLE_QUBIT_GATES",
    "TWO_QUBIT_GATES",
    "THREE_QUBIT_GATES",
    "PROVIDER_IBM",
    "PROVIDER_GOOGLE",
    "PROVIDER_AWS_BRAKET",
    "PROVIDER_AZURE_QUANTUM",
    "PROVIDER_IONQ",
    "PROVIDER_RIGETTI",
    "PROVIDER_QUANTINUUM",
    "PROVIDER_XANADU",
    "PROVIDER_LOCAL",
    "BACKEND_STATEVECTOR",
    "BACKEND_UNITARY",
    "BACKEND_MATRIX_PRODUCT_STATE",
    "BACKEND_NOISY",
    # Enums
    "GateType",
    "StateType",
    "MeasurementType",
    "BackendType",
    "ProviderType",
    "NoiseType",
    "AlgorithmType",
    "CompilerPassType",
    "JobStatus",
    "BasisType",
    "PauliType",
    "QubitState",
    "OptimizationLevel",
    "TranspilerTarget",
    # Exceptions
    "QuantumError",
    "QubitError",
    "GateError",
    "CircuitError",
    "StateError",
    "MeasurementError",
    "BackendError",
    "ProviderError",
    "CompilerError",
    "ExecutionError",
    "NoiseError",
    "AlgorithmError",
    "ParameterError",
    "ValidationError",
    "SerializationError",
    # Types
    "QubitIndex",
    "QubitIndices",
    "GateParameters",
    "StateVector",
    "DensityMatrix",
    "ComplexMatrix",
    "ProbabilityDistribution",
    "MeasurementResult",
    "CircuitDepth",
    "GateCount",
    "QubitCount",
    "GateFunction",
    "MeasurementFunction",
    "OptimizationFunction",
    "CompilerPass",
    "ValidationResult",
    "ExecutionResult",
    "JobResult",
    "BackendConfig",
    "ProviderConfig",
    "NoiseConfig",
    "CompilerConfig",
    "QuantumState",
    "QuantumOperator",
    "MeasurementBasis",
    # Interfaces
    "IQubit",
    "IQuantumGate",
    "IQuantumCircuit",
    "IQuantumState",
    "IMeasurement",
    "IQuantumBackend",
    "IQuantumProvider",
    "IQuantumCompiler",
    "IQuantumJob",
    # Protocols
    "QubitProtocol",
    "QuantumGateProtocol",
    "QuantumCircuitProtocol",
    "QuantumStateProtocol",
    "MeasurementProtocol",
    "QuantumBackendProtocol",
    "QuantumProviderProtocol",
    "QuantumCompilerProtocol",
    "QuantumJobProtocol",
    # Constants
    "QUANTUM_SDK_VERSION",
    # Factories
    "QuantumFactory",
    "GateFactory",
    "StateFactory",
    "BackendFactory",
    # Serializers
    "QuantumSerializer",
    "CircuitSerializer",
    "StateSerializer",
    "GateSerializer",
    # Validators
    "QuantumValidator",
    "GateValidator",
    "CircuitValidator",
    "StateValidator",
    "MeasurementValidator",
]
