"""
Foundation Package Constants

This module defines all constants used throughout the Foundation package.
Constants provide immutable values for common concepts and configuration.

Purpose
-------
Provide centralized, type-safe constant values for the Foundation package.

Scientific Meaning
------------------
Constants represent fundamental values, limits, and configuration parameters
that are invariant across scientific computing scenarios.

Responsibilities
----------------
- Define version constants
- Define limit constants
- Define default configuration values
- Provide validation constants
- Ensure type safety for constant values

Dependencies
------------
None

Future Extensions
-----------------
- Environment-specific constants
- Localization support
- Dynamic constant loading
- Runtime constant validation
"""

from __future__ import annotations

# Version Constants
FOUNDATION_VERSION = "0.3.0"
FOUNDATION_API_VERSION = "1.0.0"
SERIALIZATION_VERSION = "1.0.0"

# String Length Limits
MAX_NAME_LENGTH = 256
MAX_LABEL_LENGTH = 64
MAX_TYPE_LENGTH = 128
MAX_DESCRIPTION_LENGTH = 4096
MAX_METADATA_KEY_LENGTH = 128
MAX_METADATA_VALUE_LENGTH = 4096

# Numeric Limits
MAX_ENTITY_COUNT = 10_000_000
MAX_PROPERTY_COUNT = 10_000
MAX_RELATIONSHIP_COUNT = 100_000
MAX_CONSTRAINT_COUNT = 10_000
MAX_HISTORY_LENGTH = 10_000
MAX_OBSERVATION_COUNT = 1_000_000

# Time Constants
DEFAULT_TIMESTAMP_PRECISION = 6  # microseconds
MAX_FUTURE_TIME_SECONDS = 315360000  # 10 years in seconds
MAX_PAST_TIME_SECONDS = 315360000  # 10 years in seconds

# Space Constants
MAX_DIMENSION = 1024
MIN_DIMENSION = 1
DEFAULT_DIMENSION = 3

# Validation Constants
MIN_CONFIDENCE = 0.0
MAX_CONFIDENCE = 1.0
DEFAULT_CONFIDENCE = 0.5

# Serialization Constants
DEFAULT_SERIALIZATION_FORMAT = "json"
MAX_SERIALIZATION_SIZE_BYTES = 100 * 1024 * 1024  # 100 MB

# Performance Constants
DEFAULT_BATCH_SIZE = 1000
MAX_BATCH_SIZE = 10000
DEFAULT_TIMEOUT_SECONDS = 30
MAX_TIMEOUT_SECONDS = 3600

# Logging Constants
DEFAULT_LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Default Values
DEFAULT_ENTITY_TYPE = "entity"
DEFAULT_SYSTEM_TYPE = "system"
DEFAULT_PROPERTY_TYPE = "property"
DEFAULT_ATTRIBUTE_TYPE = "attribute"
DEFAULT_BEHAVIOUR_TYPE = "behaviour"
DEFAULT_RELATIONSHIP_TYPE = "relationship"
DEFAULT_CONSTRAINT_TYPE = "constraint"
DEFAULT_EVENT_TYPE = "event"
DEFAULT_OBSERVATION_TYPE = "observation"
DEFAULT_KNOWLEDGE_TYPE = "knowledge"
DEFAULT_TRANSFORMATION_TYPE = "transformation"
DEFAULT_SPACE_TYPE = "euclidean"
DEFAULT_TIME_TYPE = "continuous"

# Metadata Keys
METADATA_VERSION_KEY = "version"
METADATA_CREATED_AT_KEY = "created_at"
METADATA_UPDATED_AT_KEY = "updated_at"
METADATA_CREATED_BY_KEY = "created_by"
METADATA_SOURCE_KEY = "source"

# Reserved Property Names
RESERVED_PROPERTY_NAMES = {
    "id",
    "uuid",
    "name",
    "label",
    "type",
    "metadata",
    "state",
    "history",
    "version",
    "created_at",
    "updated_at",
}

# Validation Messages
VALIDATION_SUCCESS = "Validation passed"
VALIDATION_FAILED = "Validation failed"
CONSTRAINT_VIOLATED = "Constraint violated"
INVALID_STATE = "Invalid state"
INVALID_TRANSITION = "Invalid transition"

# Error Codes
ERROR_CODE_PREFIX = "FND"
ERROR_INVALID_STATE = f"{ERROR_CODE_PREFIX}_001"
ERROR_INVALID_LIFECYCLE = f"{ERROR_CODE_PREFIX}_002"
ERROR_CONSTRAINT_VIOLATION = f"{ERROR_CODE_PREFIX}_003"
ERROR_INVALID_IDENTITY = f"{ERROR_CODE_PREFIX}_004"
ERROR_DUPLICATE_ENTITY = f"{ERROR_CODE_PREFIX}_005"
ERROR_ENTITY_NOT_FOUND = f"{ERROR_CODE_PREFIX}_006"
ERROR_INVALID_PROPERTY = f"{ERROR_CODE_PREFIX}_007"
ERROR_PROPERTY_NOT_FOUND = f"{ERROR_CODE_PREFIX}_008"
ERROR_INVALID_RELATIONSHIP = f"{ERROR_CODE_PREFIX}_009"
ERROR_RELATIONSHIP_NOT_FOUND = f"{ERROR_CODE_PREFIX}_010"
ERROR_INVALID_CONSTRAINT = f"{ERROR_CODE_PREFIX}_011"
ERROR_CONSTRAINT_NOT_FOUND = f"{ERROR_CODE_PREFIX}_012"
ERROR_INVALID_INTERACTION = f"{ERROR_CODE_PREFIX}_013"
ERROR_INTERACTION_FAILED = f"{ERROR_CODE_PREFIX}_014"
ERROR_INVALID_BEHAVIOUR = f"{ERROR_CODE_PREFIX}_015"
ERROR_BEHAVIOUR_FAILED = f"{ERROR_CODE_PREFIX}_016"
ERROR_INVALID_EVENT = f"{ERROR_CODE_PREFIX}_017"
ERROR_EVENT_NOT_FOUND = f"{ERROR_CODE_PREFIX}_018"
ERROR_INVALID_OBSERVATION = f"{ERROR_CODE_PREFIX}_019"
ERROR_INVALID_KNOWLEDGE = f"{ERROR_CODE_PREFIX}_020"
ERROR_KNOWLEDGE_FAILED = f"{ERROR_CODE_PREFIX}_021"
ERROR_INVALID_TRANSFORMATION = f"{ERROR_CODE_PREFIX}_022"
ERROR_TRANSFORMATION_FAILED = f"{ERROR_CODE_PREFIX}_023"
ERROR_INVALID_SPACE = f"{ERROR_CODE_PREFIX}_024"
ERROR_INVALID_TIME = f"{ERROR_CODE_PREFIX}_025"
ERROR_SERIALIZATION_FAILED = f"{ERROR_CODE_PREFIX}_026"
ERROR_DESERIALIZATION_FAILED = f"{ERROR_CODE_PREFIX}_027"
ERROR_VALIDATION_FAILED = f"{ERROR_CODE_PREFIX}_028"
ERROR_CREATION_FAILED = f"{ERROR_CODE_PREFIX}_029"
ERROR_CONFIGURATION_INVALID = f"{ERROR_CODE_PREFIX}_030"

# Export all constants
__all__ = [
    # Version
    "FOUNDATION_VERSION",
    "FOUNDATION_API_VERSION",
    "SERIALIZATION_VERSION",
    # String Length Limits
    "MAX_NAME_LENGTH",
    "MAX_LABEL_LENGTH",
    "MAX_TYPE_LENGTH",
    "MAX_DESCRIPTION_LENGTH",
    "MAX_METADATA_KEY_LENGTH",
    "MAX_METADATA_VALUE_LENGTH",
    # Numeric Limits
    "MAX_ENTITY_COUNT",
    "MAX_PROPERTY_COUNT",
    "MAX_RELATIONSHIP_COUNT",
    "MAX_CONSTRAINT_COUNT",
    "MAX_HISTORY_LENGTH",
    "MAX_OBSERVATION_COUNT",
    # Time Constants
    "DEFAULT_TIMESTAMP_PRECISION",
    "MAX_FUTURE_TIME_SECONDS",
    "MAX_PAST_TIME_SECONDS",
    # Space Constants
    "MAX_DIMENSION",
    "MIN_DIMENSION",
    "DEFAULT_DIMENSION",
    # Validation Constants
    "MIN_CONFIDENCE",
    "MAX_CONFIDENCE",
    "DEFAULT_CONFIDENCE",
    # Serialization Constants
    "DEFAULT_SERIALIZATION_FORMAT",
    "MAX_SERIALIZATION_SIZE_BYTES",
    # Performance Constants
    "DEFAULT_BATCH_SIZE",
    "MAX_BATCH_SIZE",
    "DEFAULT_TIMEOUT_SECONDS",
    "MAX_TIMEOUT_SECONDS",
    # Logging Constants
    "DEFAULT_LOG_LEVEL",
    "LOG_FORMAT",
    # Default Values
    "DEFAULT_ENTITY_TYPE",
    "DEFAULT_SYSTEM_TYPE",
    "DEFAULT_PROPERTY_TYPE",
    "DEFAULT_ATTRIBUTE_TYPE",
    "DEFAULT_BEHAVIOUR_TYPE",
    "DEFAULT_RELATIONSHIP_TYPE",
    "DEFAULT_CONSTRAINT_TYPE",
    "DEFAULT_EVENT_TYPE",
    "DEFAULT_OBSERVATION_TYPE",
    "DEFAULT_KNOWLEDGE_TYPE",
    "DEFAULT_TRANSFORMATION_TYPE",
    "DEFAULT_SPACE_TYPE",
    "DEFAULT_TIME_TYPE",
    # Metadata Keys
    "METADATA_VERSION_KEY",
    "METADATA_CREATED_AT_KEY",
    "METADATA_UPDATED_AT_KEY",
    "METADATA_CREATED_BY_KEY",
    "METADATA_SOURCE_KEY",
    # Reserved Property Names
    "RESERVED_PROPERTY_NAMES",
    # Validation Messages
    "VALIDATION_SUCCESS",
    "VALIDATION_FAILED",
    "CONSTRAINT_VIOLATED",
    "INVALID_STATE",
    "INVALID_TRANSITION",
    # Error Codes
    "ERROR_CODE_PREFIX",
    "ERROR_INVALID_STATE",
    "ERROR_INVALID_LIFECYCLE",
    "ERROR_CONSTRAINT_VIOLATION",
    "ERROR_INVALID_IDENTITY",
    "ERROR_DUPLICATE_ENTITY",
    "ERROR_ENTITY_NOT_FOUND",
    "ERROR_INVALID_PROPERTY",
    "ERROR_PROPERTY_NOT_FOUND",
    "ERROR_INVALID_RELATIONSHIP",
    "ERROR_RELATIONSHIP_NOT_FOUND",
    "ERROR_INVALID_CONSTRAINT",
    "ERROR_CONSTRAINT_NOT_FOUND",
    "ERROR_INVALID_INTERACTION",
    "ERROR_INTERACTION_FAILED",
    "ERROR_INVALID_BEHAVIOUR",
    "ERROR_BEHAVIOUR_FAILED",
    "ERROR_INVALID_EVENT",
    "ERROR_EVENT_NOT_FOUND",
    "ERROR_INVALID_OBSERVATION",
    "ERROR_INVALID_KNOWLEDGE",
    "ERROR_KNOWLEDGE_FAILED",
    "ERROR_INVALID_TRANSFORMATION",
    "ERROR_TRANSFORMATION_FAILED",
    "ERROR_INVALID_SPACE",
    "ERROR_INVALID_TIME",
    "ERROR_SERIALIZATION_FAILED",
    "ERROR_DESERIALIZATION_FAILED",
    "ERROR_VALIDATION_FAILED",
    "ERROR_CREATION_FAILED",
    "ERROR_CONFIGURATION_INVALID",
]
