"""ML-domain objectives of the QMQ-10 AI/ML Intelligence layer.

Objectives operate on the domain variable names generated by the
deterministic ML naming conventions (:mod:`quantsmind.quantum.ml._expr`) and
are translated into :class:`quantsmind.quantum.core.objective.Objective`
instances (MAXIMIZE / MINIMIZE Qubit) at formulation time.

Supported objective families:

* :class:`ClassificationLossObjective` — minimize the sum of squared
  residuals of a binary-coefficient linear classifier fit,
* :class:`RegressionLossObjective` — minimize the sum of squared residuals of
  a binary-coefficient linear regression fit (identical expansion; the two
  families differ in the target semantics: class indices vs continuous
  response),
* :class:`ModelSelectionObjective` — minimize ``validation_loss +
  complexity_penalty`` of the selected candidate (one-hot),
* :class:`HyperparameterObjective` — maximize the total gain of the selected
  choices (one-hot per hyperparameter),
* :class:`MLFeatureSelectionObjective` / :class:`MLClusteringDistanceObjective`
  — delegated to the QMQ-09 Data layer at formulation time.

Every objective serializes through :meth:`to_dict`/:meth:`from_dict` and
validates against a concrete :class:`MLProblem` (passed positionally so
validation sees the dataset / problem type / candidates / k).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, ClassVar

from quantsmind.quantum.ml._expr import (
    coefficient_variable_names,
    fmt_number,
    hyperparameter_variable_name,
    linear_string,
    selection_variable_names,
)
from quantsmind.quantum.ml._validation import check_nonempty_name, check_nonnegative
from quantsmind.quantum.ml.errors import MLValidationError

if TYPE_CHECKING:
    from quantsmind.quantum.core.objective import Objective
    from quantsmind.quantum.ml.problem import MLProblem

__all__ = [
    "MLObjective",
    "ClassificationLossObjective",
    "RegressionLossObjective",
    "ModelSelectionObjective",
    "HyperparameterObjective",
    "MLFeatureSelectionObjective",
    "MLClusteringDistanceObjective",
    "objective_from_dict",
]


@dataclass
class MLObjective:
    """Base class of all ML objectives.

    Subclasses override :attr:`kind`, :meth:`validate` and
    :meth:`to_quantum_objective`.
    """

    name: str
    description: str = ""
    kind: ClassVar[str] = "ml"

    def __post_init__(self) -> None:
        try:
            check_nonempty_name(self.name, label="objective name")
        except MLValidationError as exc:
            raise MLValidationError(str(exc)) from exc

    def validate(self, problem: MLProblem) -> list[str]:
        """Return deterministic validation issues for ``problem``."""
        return []

    def to_quantum_objective(self, problem: MLProblem) -> Objective:
        """Translate into the QMQ core :class:`Objective` (Qubit MAX/MIN)."""
        raise NotImplementedError

    def to_data_objective(self, problem: MLProblem | None = None) -> Any:
        """Translate into a QMQ-09 data objective (delegated objectives only)."""
        raise MLValidationError(f"objective {self.kind!r} is not delegated to the data layer")

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-safe dictionary."""
        return {"kind": self.kind, "name": self.name, "description": self.description}

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> MLObjective:
        """Rebuild an objective from :meth:`to_dict` output."""
        return cls(name=str(data["name"]), description=str(data.get("description", "")))

    @property
    def domain(self) -> str:
        """ML-domain label of this objective."""
        return f"ml/{self.kind}"


@dataclass
class ClassificationLossObjective(MLObjective):
    """Minimize the sum of squared residuals of a least-squares fit.

    The objective fits ``y_i ~= sum_f w_f * x_if`` with **binary**
    coefficients selected to minimize :math:`SSR = sum_i (y_i - sum_f w_f x_if)^2`.
    Expanding the square turns the problem into a real quadratic binary QUBO
    whose linear coefficients are ``sum_i x_if^2 - 2 sum_i y_i x_if`` and whose
    pairwise coefficients are ``2 sum_i x_if x_ig`` (diagonal terms fold into
    the linear part because ``w_f^2 = w_f``).  No training is performed; the
    targets are the supplied numeric class labels.
    """

    kind: ClassVar[str] = "classification_loss"

    def validate(self, problem: MLProblem) -> list[str]:
        issues: list[str] = []
        if problem.problem_type.name != "CLASSIFICATION":
            issues.append("ClassificationLossObjective is only valid for classification problems")
        if problem.dataset is None:
            issues.append("classification requires a dataset")
        return issues

    def to_quantum_objective(self, problem: MLProblem) -> Objective:
        return _least_squares_objective(problem, name=self.name, kind=self.kind)


@dataclass
class RegressionLossObjective(MLObjective):
    """Minimize the sum of squared residuals of a regression fit.

    Identical expansion to :class:`ClassificationLossObjective`; the targets
    are continuous response values instead of class labels.
    """

    kind: ClassVar[str] = "regression_loss"

    def validate(self, problem: MLProblem) -> list[str]:
        issues: list[str] = []
        if problem.problem_type.name != "REGRESSION":
            issues.append("RegressionLossObjective is only valid for regression problems")
        if problem.dataset is None:
            issues.append("regression requires a dataset")
        return issues

    def to_quantum_objective(self, problem: MLProblem) -> Objective:
        return _least_squares_objective(problem, name=self.name, kind=self.kind)


@dataclass
class ModelSelectionObjective(MLObjective):
    """Minimize the selected candidate's ``validation_loss + complexity_penalty``.

    The one-hot objective ``sum_c (loss_c + penalty_c) * s_c`` is translated
    as a Qubit MINIMIZE objective over the candidate variables.  Candidate
    metrics are supplied by the caller; no training is performed.
    """

    kind: ClassVar[str] = "model_selection"

    def validate(self, problem: MLProblem) -> list[str]:
        issues: list[str] = []
        if problem.problem_type.name != "MODEL_SELECTION":
            issues.append("ModelSelectionObjective is only valid for model-selection problems")
        if not problem.candidates:
            issues.append("model selection requires at least one candidate")
        return issues

    def to_quantum_objective(self, problem: MLProblem) -> Objective:
        candidates = problem.candidates
        coefficients = [candidate.objective() for candidate in candidates]
        expression = linear_string(coefficients, selection_variable_names(len(candidates)))
        from quantsmind.quantum.core.objective import Objective, ObjectiveSense

        return Objective(
            self.name,
            ObjectiveSense.MINIMIZE,
            expression=expression,
            metadata={"ml_kind": self.kind},
        )


@dataclass
class HyperparameterObjective(MLObjective):
    """Maximize the total gain of the selected hyperparameter choices.

    The one-hot objective ``sum_{p,c} gain_{p,c} * h_{p,c}`` is translated as
    a Qubit MAXIMIZE objective over the per-parameter choice variables.  The
    search space is deterministic and finite (supplied choices only); no
    search heuristic is involved.
    """

    kind: ClassVar[str] = "hyperparameter"

    def validate(self, problem: MLProblem) -> list[str]:
        issues: list[str] = []
        if problem.problem_type.name != "HYPERPARAMETER_OPTIMIZATION":
            issues.append("HyperparameterObjective is only valid for hyperparameter problems")
        if not problem.hyperparameters:
            issues.append("hyperparameter optimization requires at least one hyperparameter")
        return issues

    def to_quantum_objective(self, problem: MLProblem) -> Objective:
        gains: list[float] = []
        names: list[str] = []
        for param_index, hyperparameter in enumerate(problem.hyperparameters):
            for choice_index, choice in enumerate(hyperparameter.choices):
                gains.append(float(choice.gain))
                names.append(hyperparameter_variable_name(param_index, choice_index))
        expression = linear_string(gains, names)
        from quantsmind.quantum.core.objective import Objective, ObjectiveSense

        return Objective(
            self.name,
            ObjectiveSense.MAXIMIZE,
            expression=expression,
            metadata={"ml_kind": self.kind},
        )


@dataclass
class MLFeatureSelectionObjective(MLObjective):
    """Combined utility-minus-cost objective for delegated feature selection.

    Delegated to the QMQ-09 Data layer: converted into a Data
    ``FeatureSelectionObjective`` (utility minus ``penalty * cost``) at
    formulation time.
    """

    utilities: dict[str, float] = field(default_factory=dict)
    costs: dict[str, float] = field(default_factory=dict)
    penalty: float = 1.0
    kind: ClassVar[str] = "ml_feature_selection"

    def __post_init__(self) -> None:
        super().__post_init__()
        for name, value in self.utilities.items():
            try:
                check_nonnegative(value, label=f"utility of feature {name!r}")
            except MLValidationError as exc:
                raise MLValidationError(str(exc)) from exc
        for name, value in self.costs.items():
            try:
                check_nonnegative(value, label=f"cost of feature {name!r}")
            except MLValidationError as exc:
                raise MLValidationError(str(exc)) from exc
        try:
            check_nonnegative(self.penalty, label="feature-selection penalty")
        except MLValidationError as exc:
            raise MLValidationError(str(exc)) from exc

    def validate(self, problem: MLProblem) -> list[str]:
        issues: list[str] = []
        if problem.problem_type.name != "FEATURE_SELECTION":
            issues.append(
                "MLFeatureSelectionObjective is only valid for feature-selection problems"
            )
        if problem.dataset is not None:
            unknown = sorted(
                (set(self.utilities) | set(self.costs)) - set(problem.dataset.feature_names)
            )
            if unknown:
                issues.append(f"unknown features in feature-selection objective: {unknown}")
        return issues

    def to_quantum_objective(self, problem: MLProblem) -> Objective:
        raise NotImplementedError(
            "MLFeatureSelectionObjective is delegated to the QMQ-09 Data layer"
        )

    def to_data_objective(self, problem: MLProblem | None = None) -> Any:
        """Return the equivalent QMQ-09 Data objective."""
        from quantsmind.quantum.data.objectives import FeatureSelectionObjective

        return FeatureSelectionObjective(
            name=self.name,
            description=self.description,
            utilities=dict(self.utilities),
            costs=dict(self.costs),
            penalty=float(self.penalty),
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "name": self.name,
            "description": self.description,
            "utilities": {name: float(value) for name, value in self.utilities.items()},
            "costs": {name: float(value) for name, value in self.costs.items()},
            "penalty": float(self.penalty),
        }


@dataclass
class MLClusteringDistanceObjective(MLObjective):
    """Delegated clustering distance objective (QMQ-09 Data layer).

    Converted into the Data ``ClusteringDistanceObjective`` at formulation
    time; clustering runs as a real quadratic binary QUBO.
    """

    kind: ClassVar[str] = "ml_clustering_distance"

    def validate(self, problem: MLProblem) -> list[str]:
        issues: list[str] = []
        if problem.problem_type.name != "CLUSTERING":
            issues.append("MLClusteringDistanceObjective is only valid for clustering problems")
        if problem.dataset is None:
            issues.append("clustering requires a dataset")
        if problem.k is None or problem.k < 1:
            issues.append("clustering requires a positive cluster count (k)")
        return issues

    def to_quantum_objective(self, problem: MLProblem) -> Objective:
        raise NotImplementedError(
            "MLClusteringDistanceObjective is delegated to the QMQ-09 Data layer"
        )

    def to_data_objective(self, problem: MLProblem | None = None) -> Any:
        """Return the equivalent QMQ-09 Data objective."""
        from quantsmind.quantum.data.objectives import ClusteringDistanceObjective

        return ClusteringDistanceObjective(name=self.name, description=self.description)


def objective_from_dict(data: dict[str, Any]) -> MLObjective:
    """Rebuild any supported ML objective from :meth:`to_dict` output."""
    kind = str(data.get("kind", ""))
    name = str(data["name"])
    description = str(data.get("description", ""))
    if kind == "classification_loss":
        return ClassificationLossObjective(name=name, description=description)
    if kind == "regression_loss":
        return RegressionLossObjective(name=name, description=description)
    if kind == "model_selection":
        return ModelSelectionObjective(name=name, description=description)
    if kind == "hyperparameter":
        return HyperparameterObjective(name=name, description=description)
    if kind == "ml_feature_selection":
        return MLFeatureSelectionObjective(
            name=name,
            description=description,
            utilities={n: float(v) for n, v in data.get("utilities", {}).items()},
            costs={n: float(v) for n, v in data.get("costs", {}).items()},
            penalty=float(data.get("penalty", 1.0)),
        )
    if kind == "ml_clustering_distance":
        return MLClusteringDistanceObjective(name=name, description=description)
    raise MLValidationError(f"unknown ML objective kind {kind!r}")


def _least_squares_objective(problem: MLProblem, *, name: str, kind: str) -> Objective:
    """Build the Qubit MINIMIZE objective of a binary-coefficient fit.

    With binary coefficients ``w_f`` the sum of squared residuals
    ``SSR = sum_i (y_i - sum_f w_f x_if)^2`` expands to
    ``sum_i y_i^2 - 2 sum_f w_f sum_i y_i x_if + sum_f w_f sum_i x_if^2
    + 2 sum_{f<g} w_f w_g sum_i x_if x_ig`` (diagonal terms fold into the
    linear part because ``w_f^2 = w_f``).
    """
    from quantsmind.quantum.core.objective import Objective, ObjectiveSense

    dataset = problem.dataset
    if dataset is None:
        raise MLValidationError("a dataset is required to build a fitting objective")
    matrix = dataset.matrix()
    targets = dataset.targets()
    num_features = len(dataset.feature_names)
    variable_names = coefficient_variable_names(num_features)

    linear = [0.0] * num_features
    quad_terms: list[tuple[str, str, float]] = []
    for record, target in zip(matrix, targets, strict=True):
        for f in range(num_features):
            value = float(record[f])
            linear[f] += value * value - 2.0 * float(target) * value
        for f in range(num_features):
            for g in range(f + 1, num_features):
                coefficient = 2.0 * float(record[f]) * float(record[g])
                if coefficient != 0.0:
                    quad_terms.append((variable_names[f], variable_names[g], coefficient))
    constant = float(sum(target * target for target in targets))

    parts: list[str] = []
    if constant != 0.0:
        parts.append(fmt_number(constant))
    linear_parts = [
        f"{fmt_number(c)}*{v}" for v, c in zip(variable_names, linear, strict=True) if c != 0.0
    ]
    parts.extend(linear_parts)
    parts.extend(f"{fmt_number(c)}*{left}*{right}" for left, right, c in quad_terms)
    expression = " + ".join(parts) if parts else "0"
    return Objective(
        name,
        ObjectiveSense.MINIMIZE,
        expression=expression,
        metadata={"ml_kind": kind, "constant_term": constant},
    )
