"""QuantsMind Quantum — domain-intelligence layer.

``quantsmind.quantum`` is **not** a quantum computing engine.  It is the
*domain-intelligence layer* of the QuantsMind SDK that connects QuantsMind's
scientific and domain abstractions to the MicroQuantum quantum SDK.

The dependency direction is always::

    Domain Systems -> QuantsMind Quantum -> MicroQuantum

MicroQuantum never imports QuantsMind.

Architecture (QMQ-01 + QMQ-02 + QMQ-03)
-----------------------------------------
* **core** — domain objects: ``QuantumProblem``, ``Variable``,
  ``Objective``, ``Constraint``, ``DomainContext``, ``ProblemSolution``.
* **formulation** — structural problem representations:
  ``MathematicalModel``, ``OptimizationModel``, ``GraphModel``,
  ``MLModel``, ``SimulationModel``, ``StatisticalModel``; plus
  :func:`formulate` and :func:`model_from_dict`.
* **strategy** — computation strategy selection:
  ``ComputationStrategy`` enum + deterministic ``StrategySelector``
  (QMQ-01 size rules; QMQ-03 reasoned path ``select_reasoned``).
* **intelligence** — QMQ-03 algorithm & computational strategy
  intelligence: ``ProblemClassifier``, ``FormulationRecommender``,
  ``AlgorithmSelector`` + ``AlgorithmRegistry``, ``CapabilityModel`` and
  ``ComputationPlan``.
* **mapping** — program -> runtime object: ``QuantumCircuitMapper`` (real
  MicroQuantum path); ``ProblemMapper`` / ``QUBOMapper`` / ``IsingMapper``
  implement the automatic problem -> QUBO -> Ising pipeline.
* **optimization** — QMQ-02 mathematical formulation: symbolic
  expressions, ``QUBOModel``, ``IsingModel``, constraint penalties and the
  classical exhaustive baseline.
* **workflow** — end-to-end pipeline: ``QuantumWorkflow`` (QMQ-04 adds
  execution options, a lifecycle state machine and deterministic hybrid
  comparison/selection).
* **execution** — QMQ-04 executors: ``ClassicalExecutor``,
  ``QuantumExecutor``, ``HybridExecutor`` + ``ExecutionComparison`` and the
  typed failure taxonomy (``WorkflowError``,
  ``MicroQuantumUnavailableError``, ...).
* **result** — domain-level solution artifacts: ``SolutionReport``,
  ``Interpretation`` + ``Provenance``, and QMQ-06 structured result
  interpretation (``ResultInterpreter`` / ``ResultInterpretation``);
  low-level ``QuantumResult`` lives in
  :mod:`quantsmind.quantum.circuit_result`.
* **integration** — MicroQuantum facade: lazy ``require_microquantum``,
  ``microquantum_available``, ``resolve_backend``, and the QMQ-02 QAOA
  delegation (``run_qaoa``).
* **finance** — QMQ-07/08 Finance domain foundation.  QMQ-07 ships
  ``Asset`` / ``AssetUniverse`` / ``FinancialProblem`` /
  ``FinancialContext`` / ``RiskMatrix`` / ``Budget`` / allocation weights,
  financial constraints and objectives, the ``FinanceFormulationAdapter``
  (finance -> existing QMQ formulation) and deterministic asset <->
  variable mapping with solution decoding.  QMQ-08 builds the portfolio
  layer on top: ``PortfolioOptimizationProblem``, ``PortfolioMetrics``,
  ``PortfolioComponent`` / ``PortfolioSolution`` /
  ``PortfolioOptimizationResult`` and ``PortfolioOptimizer`` (runs the
  existing workflow/benchmark/interpretation pipeline; binary selection is
  fully supported, continuous allocation is validated/formulated but the
  binary-only QUBO pipeline surfaces honest errors instead of
  approximating, integer allocation raises validation errors).  Works
  entirely from supplied data, never live feeds.
* **data** — QMQ-09 Data Intelligence foundation.  ``DataFeature`` /
  ``DataRecord`` / ``DataSet`` / ``FeatureVector`` observations, distance &
  similarity primitives, pairwise ``DataRelationship`` builders and
  deterministic ``DataQualityReport`` assessment; feature-selection
  objectives/constraints and clustering as a real quadratic binary QUBO;
  the ``DataProblem`` type, ``DataFormulationAdapter`` (data -> existing
  QMQ formulation), deterministic ``DataMapper`` decoding,
  ``DataMetrics``, ``DataSolution`` and ``DataOptimizer`` (runs the
  existing workflow/benchmark/interpretation pipeline).  Works entirely
  from supplied/synthetic data — no ML framework, no live data.
* **ml** — QMQ-10 AI/ML Intelligence foundation.  ``MLFeature`` /
  ``MLRecord`` / ``MLDataSet`` observations with targets, least-squares
  classification/regression objectives over binary coefficients, one-hot
  model-selection and per-parameter hyperparameter objectives, and ML
  constraint families; the ``MLProblem`` type,
  ``MLFormulationAdapter`` (ml -> existing QMQ formulation; feature
  selection and clustering are fully delegated to the QMQ-09 Data layer),
  deterministic ``MLMapper`` decoding, ``MLMetrics``, ML domain
  ``ClassificationSolution`` / ``RegressionSolution`` /
  ``ModelSelectionSolution`` / ``HyperparameterSolution`` and the
  ``MLOptimizer`` (runs the existing workflow/benchmark/interpretation
  pipeline).  Works entirely from supplied data — no ML framework
  dependencies, ``scikit-learn`` and friends are never required.

Importing this package never requires ``microquantum`` to be installed.
MicroQuantum is only imported lazily when a quantum execution API is
called.
"""

from __future__ import annotations

from quantsmind.quantum._mq import microquantum_available
from quantsmind.quantum.benchmark import (
    BaselineConfig,
    Benchmark,
    BenchmarkComparison,
    BenchmarkMetrics,
    BenchmarkResult,
    BenchmarkRunner,
    BenchmarkRunSummary,
    BenchmarkSuite,
    BenchmarkWinner,
    approximation_ratio,
    b1_knapsack,
    b2_linear_max,
    b3_qubo_min,
    b4_maxcut_triangle,
    b5_geq_max,
    constraint_violations,
    default_suite,
    default_suite_examples,
    is_better,
    metrics_rank_key,
    normalized_score,
    objective_sense,
    optimality_gap,
    sense_label,
)
from quantsmind.quantum.bridge import (
    GateParamError,
    UnknownGateError,
    build_circuit,
    validate_program,
)
from quantsmind.quantum.circuit_result import QuantumResult, to_microquantum_result
from quantsmind.quantum.core import (
    Constraint,
    ConstraintOperator,
    ConstraintPriority,
    ConstraintStatus,
    DomainContext,
    Objective,
    ObjectiveSense,
    ProblemSolution,
    QuantumProblem,
    Variable,
    VariableType,
)
from quantsmind.quantum.data import (
    AssignmentConstraint,
    ClusterCountConstraint,
    ClusteringDistanceObjective,
    DataConstraint,
    DataContext,
    DataError,
    DataFeature,
    DataFormulationAdapter,
    DataMapper,
    DataMapping,
    DataMetrics,
    DataObjective,
    DataOptimizationConfiguration,
    DataOptimizationResult,
    DataOptimizer,
    DataProblem,
    DataProblemType,
    DataQualityReport,
    DataRecord,
    DataRelationship,
    DataSet,
    DataSolution,
    DataValidationError,
    DecodedClusterAssignment,
    DecodedDataFeature,
    FeatureCountConstraint,
    FeatureGroupConstraint,
    FeatureSelectionObjective,
    FeatureUtilityObjective,
    FeatureVector,
    SelectionCostObjective,
    all_examples,
    assess_data_quality,
    clustering_example,
    data_context_example,
    dataset_example,
    euclidean_distance,
    feature_selection_example,
    grouped_feature_selection_example,
    pairwise_relationship,
    quality_example,
    selection_cost_example,
    serialization_example,
    similarity_example,
    similarity_from_distance,
    squared_euclidean_distance,
    weighted_squared_euclidean_distance,
)
from quantsmind.quantum.domain import (
    DomainBinding,
    DomainDispatchError,
    DomainError,
    DomainIntelligence,
    DomainKind,
    DomainRegistry,
    DomainRunResult,
    DomainValidationError,
    ExecutionPlan,
    ProblemAssessment,
    QuantumSuitability,
    QuantumSuitabilityAssessor,
    SuitabilityAssessment,
    UnsupportedDomainError,
    assess_problem,
    domain_data_example,
    domain_finance_example,
    domain_ml_example,
    domain_pipeline_example,
)
from quantsmind.quantum.execution import (
    ClassicalExecutionError,
    ClassicalExecutionResult,
    ClassicalExecutor,
    ExecutionComparison,
    ExecutionComparisonEntry,
    ExecutionError,
    ExecutionOptions,
    Executor,
    ExecutorContext,
    HybridExecutionError,
    HybridExecutionResult,
    HybridExecutor,
    InvalidExecutionOptionError,
    InvalidQuantumResultError,
    MicroQuantumUnavailableError,
    QuantumExecutionError,
    QuantumExecutionResult,
    QuantumExecutor,
    UnsupportedStrategyError,
    WorkflowError,
)
from quantsmind.quantum.experiment import (
    QuantumExperiment,
    available_algorithms,
    resolve_algorithm,
    run_algorithm,
)
from quantsmind.quantum.finance import (
    Allocation,
    AllocationKind,
    Asset,
    AssetMapping,
    AssetUniverse,
    Budget,
    BudgetConstraint,
    CardinalityConstraint,
    DecodedAsset,
    ExpectedReturnObjective,
    FinanceAssetMapper,
    FinanceError,
    FinanceFormulationAdapter,
    FinanceOptimizationResult,
    FinanceOptimizer,
    FinanceValidationError,
    FinancialConstraint,
    FinancialContext,
    FinancialInstrument,
    FinancialObjective,
    FinancialProblem,
    FinancialSolution,
    GroupAllocationConstraint,
    OptimizationConfiguration,
    PortfolioAssetMapper,
    PortfolioComponent,
    PortfolioFormulationAdapter,
    PortfolioMetrics,
    PortfolioOptimizationProblem,
    PortfolioOptimizationResult,
    PortfolioOptimizer,
    PortfolioSolution,
    PositionLimitConstraint,
    RiskAdjustedObjective,
    RiskMatrix,
    RiskObjective,
    WeightBoundsConstraint,
    compute_portfolio_metrics,
    constraint_from_dict,
    example_asset_universe,
    example_budget,
    example_budget_portfolio,
    example_combined_problem,
    example_financial_problem,
    example_group_constraints_portfolio,
    example_maximize_return_portfolio,
    example_minimize_risk_portfolio,
    example_portfolio_problem,
    example_portfolio_risk_matrix,
    example_portfolio_universe,
    example_return_problem,
    example_risk_adjusted_portfolio,
    example_risk_matrix,
    example_risk_problem,
    expected_return_of,
    objective_from_dict,
    portfolio_variance,
    portfolio_volatility,
    risk_contributions,
    synthetic_asset,
)
from quantsmind.quantum.formulation import (
    GraphModel,
    MathematicalModel,
    MLModel,
    OptimizationModel,
    SimulationModel,
    StatisticalModel,
    formulate,
    model_from_dict,
)
from quantsmind.quantum.integration.microquantum import (
    QaoaExecutionResult,
    QuantumIntegrationError,
    ising_to_optimization_problem,
    ising_to_pauli_sum,
    qaoa_available,
    run_qaoa,
)
from quantsmind.quantum.intelligence import (
    AlgorithmAvailability,
    AlgorithmCategory,
    AlgorithmDescriptor,
    AlgorithmRecommendation,
    AlgorithmRegistry,
    AlgorithmSelectionError,
    AlgorithmSelector,
    CapabilityModel,
    ClassificationResult,
    ComputationPlan,
    DuplicateAlgorithmError,
    FormulationAlternative,
    FormulationRecommendation,
    FormulationRecommender,
    ProblemClass,
    ProblemClassifier,
    UnknownAlgorithmError,
)
from quantsmind.quantum.mapping import (
    DomainMapper,
    IsingMapper,
    MappingError,
    MappingResult,
    ProblemMapper,
    QuantumCircuitMapper,
    QUBOMapper,
)
from quantsmind.quantum.ml import (
    ClassificationLossObjective,
    ClassificationSolution,
    DecodedHyperparameterChoice,
    DecodedMLCoefficient,
    DecodedModelSelection,
    HyperparameterObjective,
    HyperparameterOnePerParameterConstraint,
    HyperparameterSolution,
    MLAssignmentConstraint,
    MLBaseSolution,
    MLClusterCountConstraint,
    MLClusteringDistanceObjective,
    MLCoefficientCountConstraint,
    MLConstraint,
    MLContext,
    MLDataSet,
    MLError,
    MLFeature,
    MLFeatureCountConstraint,
    MLFeatureSelectionObjective,
    MLFeatureSelectionSolution,
    MLFormulationAdapter,
    MLHyperparameter,
    MLHyperparameterChoice,
    MLMapper,
    MLMapping,
    MLMetrics,
    MLModelCandidate,
    MLObjective,
    MLOptimizationConfiguration,
    MLOptimizationResult,
    MLOptimizer,
    MLProblem,
    MLProblemType,
    MLRecord,
    MLValidationError,
    ModelSelectionObjective,
    ModelSelectionOneHotConstraint,
    ModelSelectionSolution,
    RegressionLossObjective,
    RegressionSolution,
    ml_all_examples,
    ml_classification_example,
    ml_clustering_example,
    ml_dataset_example,
    ml_feature_selection_example,
    ml_hyperparameter_example,
    ml_model_selection_example,
    ml_regression_example,
)
from quantsmind.quantum.optimization import (
    ClassicalSolverResult,
    ConstraintPenalizer,
    ExhaustiveLimitError,
    ExhaustiveSolver,
    IsingModel,
    NoFeasibleSolutionError,
    PenaltyTerm,
    QUBOModel,
    coerce_expression,
    parse_expression,
    qubo_from_expression,
)
from quantsmind.quantum.program import GateSpec, QuantumProgram
from quantsmind.quantum.result import (
    AlgorithmInterpretation,
    BenchmarkInterpretation,
    ExecutionInterpretation,
    FeasibilityInterpretation,
    FeasibilityStatus,
    Interpretation,
    InterpretationQuality,
    InterpretationStatus,
    Limitation,
    ObjectiveInterpretation,
    Provenance,
    ProvenanceOverview,
    Qualification,
    ResultInterpretation,
    ResultInterpreter,
    SolutionInterpreter,
    SolutionQuality,
    SolutionReport,
    StrategyInterpretation,
)
from quantsmind.quantum.strategy import ComputationStrategy, StrategySelector
from quantsmind.quantum.workflow import QuantumWorkflow, WorkflowState

__all__ = [
    # core domain objects
    "QuantumProblem",
    "Variable",
    "VariableType",
    "Objective",
    "ObjectiveSense",
    "Constraint",
    "ConstraintOperator",
    "ConstraintPriority",
    "ConstraintStatus",
    "DomainContext",
    "ProblemSolution",
    # low-level quantum layer
    "GateSpec",
    "QuantumProgram",
    "QuantumResult",
    "QuantumExperiment",
    "to_microquantum_result",
    "build_circuit",
    "validate_program",
    "UnknownGateError",
    "GateParamError",
    "available_algorithms",
    "resolve_algorithm",
    "run_algorithm",
    "microquantum_available",
    # formulation layer
    "MathematicalModel",
    "OptimizationModel",
    "GraphModel",
    "MLModel",
    "SimulationModel",
    "StatisticalModel",
    "formulate",
    "model_from_dict",
    # strategy layer
    "ComputationStrategy",
    "StrategySelector",
    # mapping layer
    "DomainMapper",
    "MappingError",
    "MappingResult",
    "QuantumCircuitMapper",
    "ProblemMapper",
    "QUBOMapper",
    "IsingMapper",
    # optimization layer
    "QUBOModel",
    "IsingModel",
    "ConstraintPenalizer",
    "PenaltyTerm",
    "ExhaustiveSolver",
    "ClassicalSolverResult",
    "ExhaustiveLimitError",
    "NoFeasibleSolutionError",
    "parse_expression",
    "coerce_expression",
    "qubo_from_expression",
    # integration layer
    "run_qaoa",
    "QaoaExecutionResult",
    "QuantumIntegrationError",
    "ising_to_pauli_sum",
    "ising_to_optimization_problem",
    "qaoa_available",
    # result layer
    "SolutionReport",
    "Interpretation",
    "InterpretationQuality",
    "SolutionInterpreter",
    "Provenance",
    # result interpretation layer (QMQ-06)
    "ResultInterpreter",
    "ResultInterpretation",
    "InterpretationStatus",
    "SolutionQuality",
    "FeasibilityStatus",
    "Qualification",
    "FeasibilityInterpretation",
    "ObjectiveInterpretation",
    "BenchmarkInterpretation",
    "StrategyInterpretation",
    "AlgorithmInterpretation",
    "ExecutionInterpretation",
    "ProvenanceOverview",
    "Limitation",
    # workflow layer
    "QuantumWorkflow",
    "WorkflowError",
    "WorkflowState",
    # execution layer (QMQ-04)
    "Executor",
    "ExecutorContext",
    "ExecutionOptions",
    "ClassicalExecutor",
    "ClassicalExecutionResult",
    "QuantumExecutor",
    "QuantumExecutionResult",
    "HybridExecutor",
    "HybridExecutionResult",
    "ExecutionComparison",
    "ExecutionComparisonEntry",
    "ExecutionError",
    "ClassicalExecutionError",
    "QuantumExecutionError",
    "HybridExecutionError",
    "InvalidQuantumResultError",
    "MicroQuantumUnavailableError",
    "UnsupportedStrategyError",
    "InvalidExecutionOptionError",
    # intelligence layer (QMQ-03)
    "ProblemClass",
    "ClassificationResult",
    "ProblemClassifier",
    "FormulationAlternative",
    "FormulationRecommendation",
    "FormulationRecommender",
    "AlgorithmCategory",
    "AlgorithmDescriptor",
    "AlgorithmAvailability",
    "AlgorithmRecommendation",
    "AlgorithmRegistry",
    "UnknownAlgorithmError",
    "DuplicateAlgorithmError",
    "CapabilityModel",
    "AlgorithmSelector",
    "AlgorithmSelectionError",
    "ComputationPlan",
    # finance layer (QMQ-07)
    "FinancialInstrument",
    "Asset",
    "AssetUniverse",
    "FinancialProblem",
    "FinancialContext",
    "RiskMatrix",
    "Budget",
    "AllocationKind",
    "Allocation",
    "FinancialConstraint",
    "BudgetConstraint",
    "WeightBoundsConstraint",
    "CardinalityConstraint",
    "PositionLimitConstraint",
    "GroupAllocationConstraint",
    "constraint_from_dict",
    "FinancialObjective",
    "ExpectedReturnObjective",
    "RiskObjective",
    "RiskAdjustedObjective",
    "objective_from_dict",
    "FinanceFormulationAdapter",
    "FinanceAssetMapper",
    "AssetMapping",
    "DecodedAsset",
    "FinanceError",
    "FinanceValidationError",
    "synthetic_asset",
    "example_asset_universe",
    "example_budget",
    "example_risk_matrix",
    "example_return_problem",
    "example_risk_problem",
    "example_combined_problem",
    "example_financial_problem",
    "OptimizationConfiguration",
    "PortfolioOptimizationProblem",
    "PortfolioFormulationAdapter",
    "PortfolioAssetMapper",
    "PortfolioOptimizer",
    "PortfolioMetrics",
    "compute_portfolio_metrics",
    "expected_return_of",
    "portfolio_variance",
    "portfolio_volatility",
    "risk_contributions",
    "PortfolioComponent",
    "PortfolioSolution",
    "PortfolioOptimizationResult",
    "FinancialSolution",
    "FinanceOptimizationResult",
    "FinanceOptimizer",
    "example_portfolio_universe",
    "example_portfolio_risk_matrix",
    "example_maximize_return_portfolio",
    "example_minimize_risk_portfolio",
    "example_risk_adjusted_portfolio",
    "example_budget_portfolio",
    "example_group_constraints_portfolio",
    "example_portfolio_problem",
    # data layer (QMQ-09)
    "DataFeature",
    "DataRecord",
    "DataSet",
    "FeatureVector",
    "DataContext",
    "DataRelationship",
    "pairwise_relationship",
    "DataQualityReport",
    "assess_data_quality",
    "euclidean_distance",
    "squared_euclidean_distance",
    "weighted_squared_euclidean_distance",
    "similarity_from_distance",
    "DataObjective",
    "FeatureUtilityObjective",
    "SelectionCostObjective",
    "FeatureSelectionObjective",
    "ClusteringDistanceObjective",
    "DataConstraint",
    "FeatureCountConstraint",
    "FeatureGroupConstraint",
    "AssignmentConstraint",
    "ClusterCountConstraint",
    "DataProblemType",
    "DataProblem",
    "DataFormulationAdapter",
    "DataMapper",
    "DataMapping",
    "DecodedDataFeature",
    "DecodedClusterAssignment",
    "DataMetrics",
    "DataSolution",
    "DataOptimizationResult",
    "DataOptimizationConfiguration",
    "DataOptimizer",
    "DataError",
    "DataValidationError",
    "dataset_example",
    "data_context_example",
    "feature_selection_example",
    "selection_cost_example",
    "grouped_feature_selection_example",
    "similarity_example",
    "quality_example",
    "clustering_example",
    "serialization_example",
    "all_examples",
    # ml layer (QMQ-10)
    "MLFeature",
    "MLRecord",
    "MLDataSet",
    "MLModelCandidate",
    "MLHyperparameterChoice",
    "MLHyperparameter",
    "MLContext",
    "MLObjective",
    "ClassificationLossObjective",
    "RegressionLossObjective",
    "ModelSelectionObjective",
    "HyperparameterObjective",
    "MLFeatureSelectionObjective",
    "MLClusteringDistanceObjective",
    "MLConstraint",
    "MLCoefficientCountConstraint",
    "ModelSelectionOneHotConstraint",
    "HyperparameterOnePerParameterConstraint",
    "MLFeatureCountConstraint",
    "MLAssignmentConstraint",
    "MLClusterCountConstraint",
    "MLProblemType",
    "MLProblem",
    "MLFormulationAdapter",
    "DecodedMLCoefficient",
    "DecodedModelSelection",
    "DecodedHyperparameterChoice",
    "MLMapping",
    "MLMapper",
    "MLMetrics",
    "MLBaseSolution",
    "ClassificationSolution",
    "RegressionSolution",
    "MLFeatureSelectionSolution",
    "ModelSelectionSolution",
    "HyperparameterSolution",
    "MLOptimizationResult",
    "MLOptimizationConfiguration",
    "MLOptimizer",
    "MLError",
    "MLValidationError",
    "ml_dataset_example",
    "ml_classification_example",
    "ml_regression_example",
    "ml_feature_selection_example",
    "ml_model_selection_example",
    "ml_hyperparameter_example",
    "ml_clustering_example",
    "ml_all_examples",
    # domain intelligence layer (QMQ-11)
    "DomainError",
    "DomainValidationError",
    "DomainDispatchError",
    "UnsupportedDomainError",
    "DomainKind",
    "DomainBinding",
    "DomainRegistry",
    "QuantumSuitability",
    "SuitabilityAssessment",
    "QuantumSuitabilityAssessor",
    "ProblemAssessment",
    "assess_problem",
    "ExecutionPlan",
    "DomainRunResult",
    "DomainIntelligence",
    "domain_finance_example",
    "domain_data_example",
    "domain_ml_example",
    "domain_pipeline_example",
    # benchmark layer (QMQ-05)
    "Benchmark",
    "BenchmarkSuite",
    "BenchmarkRunner",
    "BenchmarkMetrics",
    "BenchmarkComparison",
    "BenchmarkWinner",
    "BenchmarkResult",
    "BenchmarkRunSummary",
    "BaselineConfig",
    "b1_knapsack",
    "b2_linear_max",
    "b3_qubo_min",
    "b4_maxcut_triangle",
    "b5_geq_max",
    "default_suite",
    "default_suite_examples",
    "objective_sense",
    "sense_label",
    "is_better",
    "normalized_score",
    "optimality_gap",
    "approximation_ratio",
    "constraint_violations",
    "metrics_rank_key",
]
