"""Data-domain objectives of the QMQ-09 Data Intelligence layer.

Objectives operate on the domain variable names generated by the deterministic
Data naming conventions (:mod:`quantsmind.quantum.data._expr`) and are
translated into :class:`quantsmind.quantum.core.objective.Objective` instances
(MAXIMIZE / MINIMIZE Qubit) at formulation time.

Supported objective families:

* :class:`FeatureUtilityObjective`  — maximize feature utility
  (``sum_i utilities[i] * x_i``),
* :class:`SelectionCostObjective`   — minimize selection cost
  (``sum_i costs[i] * x_i``),
* :class:`FeatureSelectionObjective` — combined utility-minus-cost
  (``sum_u - penalty * sum_c``),
* :class:`ClusteringDistanceObjective` — minimize total within-cluster
  pairwise distance (``sum_c sum_{i<j} distance[i][j] * z_i_c * z_j_c``).

Every objective serializes through :meth:`to_dict`/:meth:`from_dict` and
validates against a concrete :class:`DataProblem` (passed positionally so
validation sees the dataset / problem type / k).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, ClassVar

from quantsmind.quantum.data._expr import cluster_variable_name, fmt_number, variable_name
from quantsmind.quantum.data._validation import check_nonempty_name, check_nonnegative
from quantsmind.quantum.data.errors import DataValidationError

if TYPE_CHECKING:
    from quantsmind.quantum.core.objective import Objective
    from quantsmind.quantum.data.problem import DataProblem

__all__ = [
    "DataObjective",
    "FeatureUtilityObjective",
    "SelectionCostObjective",
    "FeatureSelectionObjective",
    "ClusteringDistanceObjective",
    "objective_from_dict",
]


@dataclass
class DataObjective:
    """Base class of all data objectives.

    Subclasses override :attr:`kind`, :meth:`validate` and
    :meth:`to_quantum_objective`.
    """

    name: str
    description: str = ""
    kind: ClassVar[str] = "data"

    def __post_init__(self) -> None:
        try:
            check_nonempty_name(self.name, label="objective name")
        except ValueError as exc:
            raise DataValidationError(str(exc)) from exc

    def validate(self, problem: DataProblem) -> list[str]:
        """Return deterministic validation issues for ``problem``."""
        return []

    def to_quantum_objective(self, problem: DataProblem) -> Objective:
        """Translate into the QMQ core :class:`Objective` (Qubit MAX/MIN)."""
        raise NotImplementedError

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a JSON-safe dictionary."""
        return {"kind": self.kind, "name": self.name, "description": self.description}

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> DataObjective:
        """Rebuild an objective from :meth:`to_dict` output."""
        return cls(name=str(data["name"]), description=str(data.get("description", "")))

    @property
    def domain(self) -> str:
        """Data-domain label of this objective."""
        return f"data/{self.kind}"


@dataclass
class FeatureUtilityObjective(DataObjective):
    """Maximize the sum of selected-feature utilities.

    Args:
        name: Objective name.
        utilities: Feature name -> non-negative utility.
        description: Free-form description.
    """

    utilities: dict[str, float] = field(default_factory=dict)
    kind: ClassVar[str] = "feature_utility"

    def __post_init__(self) -> None:
        super().__post_init__()
        for name, value in self.utilities.items():
            try:
                check_nonnegative(value, label=f"utility of feature {name!r}")
            except ValueError as exc:
                raise DataValidationError(str(exc)) from exc

    def validate(self, problem: DataProblem) -> list[str]:
        issues: list[str] = []
        if problem.problem_type.name != "FEATURE_SELECTION":
            issues.append("FeatureUtilityObjective is only valid for feature-selection problems")
        unknown = sorted(set(self.utilities) - set(problem.dataset.feature_names))
        if unknown:
            issues.append(f"unknown features in utilities: {unknown}")
        return issues

    def to_quantum_objective(self, problem: DataProblem) -> Objective:
        coefficients = [self.utilities.get(name, 0.0) for name in problem.dataset.feature_names]
        return _linear_objective(coefficients, maximum=True, label=self.name)

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "name": self.name,
            "description": self.description,
            "utilities": {name: float(value) for name, value in self.utilities.items()},
        }


@dataclass
class SelectionCostObjective(DataObjective):
    """Minimize the sum of selected-feature costs.

    Args:
        name: Objective name.
        costs: Feature name -> non-negative cost.
        description: Free-form description.
    """

    costs: dict[str, float] = field(default_factory=dict)
    kind: ClassVar[str] = "selection_cost"

    def __post_init__(self) -> None:
        super().__post_init__()
        for name, value in self.costs.items():
            try:
                check_nonnegative(value, label=f"cost of feature {name!r}")
            except ValueError as exc:
                raise DataValidationError(str(exc)) from exc

    def validate(self, problem: DataProblem) -> list[str]:
        issues: list[str] = []
        if problem.problem_type.name != "FEATURE_SELECTION":
            issues.append("SelectionCostObjective is only valid for feature-selection problems")
        unknown = sorted(set(self.costs) - set(problem.dataset.feature_names))
        if unknown:
            issues.append(f"unknown features in costs: {unknown}")
        return issues

    def to_quantum_objective(self, problem: DataProblem) -> Objective:
        coefficients = [self.costs.get(name, 0.0) for name in problem.dataset.feature_names]
        return _linear_objective(coefficients, maximum=False, label=self.name)

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "name": self.name,
            "description": self.description,
            "costs": {name: float(value) for name, value in self.costs.items()},
        }


@dataclass
class FeatureSelectionObjective(DataObjective):
    """Combined feature-selection objective ``utility - penalty * cost``.

    Args:
        name: Objective name.
        utilities: Feature name -> non-negative utility.
        costs: Feature name -> non-negative cost.
        penalty: Non-negative penalty applied to the total selection cost.
        description: Free-form description.
    """

    utilities: dict[str, float] = field(default_factory=dict)
    costs: dict[str, float] = field(default_factory=dict)
    penalty: float = 1.0
    kind: ClassVar[str] = "feature_selection"

    def __post_init__(self) -> None:
        super().__post_init__()
        for name, value in self.utilities.items():
            try:
                check_nonnegative(value, label=f"utility of feature {name!r}")
            except ValueError as exc:
                raise DataValidationError(str(exc)) from exc
        for name, value in self.costs.items():
            try:
                check_nonnegative(value, label=f"cost of feature {name!r}")
            except ValueError as exc:
                raise DataValidationError(str(exc)) from exc
        try:
            check_nonnegative(self.penalty, label="feature-selection penalty")
        except ValueError as exc:
            raise DataValidationError(str(exc)) from exc

    def validate(self, problem: DataProblem) -> list[str]:
        issues: list[str] = []
        if problem.problem_type.name != "FEATURE_SELECTION":
            issues.append("FeatureSelectionObjective is only valid for feature-selection problems")
        unknown = sorted(
            (set(self.utilities) | set(self.costs)) - set(problem.dataset.feature_names)
        )
        if unknown:
            issues.append(f"unknown features in feature-selection objective: {unknown}")
        return issues

    def to_quantum_objective(self, problem: DataProblem) -> Objective:
        coefficients: list[float] = []
        for name in problem.dataset.feature_names:
            net = self.utilities.get(name, 0.0) - self.penalty * self.costs.get(name, 0.0)
            coefficients.append(net)
        return _linear_objective(coefficients, maximum=True, label=self.name)

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": self.kind,
            "name": self.name,
            "description": self.description,
            "utilities": {name: float(value) for name, value in self.utilities.items()},
            "costs": {name: float(value) for name, value in self.costs.items()},
            "penalty": float(self.penalty),
        }


@dataclass
class ClusteringDistanceObjective(DataObjective):
    """Minimize the total within-cluster pairwise distance.

    The quadratic objective
    ``sum_cluster sum_{i<j} distance(i, j) * z_i_c * z_j_c`` runs over the
    pairwise relationships of the problem's dataset (supplied explicitly as
    ``problem.pairwise`` or computed from the Data context distance metric).

    Args:
        name: Objective name.
        description: Free-form description.
    """

    kind: ClassVar[str] = "clustering_distance"

    def validate(self, problem: DataProblem) -> list[str]:
        issues: list[str] = []
        if problem.problem_type.name != "CLUSTERING":
            issues.append("ClusteringDistanceObjective is only valid for clustering problems")
        if problem.k is None or problem.k < 1:
            issues.append("clustering requires a positive cluster count (k)")
        if not problem.dataset.records:
            issues.append("clustering requires at least one record")
        if problem.pairwise is not None:
            try:
                problem.pairwise.validate_against(problem.dataset.record_ids)
            except DataValidationError as exc:
                issues.append(str(exc))
        return issues

    def to_quantum_objective(self, problem: DataProblem) -> Objective:
        distances = problem.clustering_distance_matrix()
        terms: list[tuple[str, str, float]] = []
        for record_i in range(len(problem.dataset.records)):
            for cluster in range(problem.k or 0):
                left = cluster_variable_name(record_i, cluster)
                for record_j in range(record_i + 1, len(problem.dataset.records)):
                    right = cluster_variable_name(record_j, cluster)
                    coefficient = float(distances.values[record_i][record_j])
                    if coefficient != 0.0:
                        terms.append((left, right, coefficient))
        expression = (
            " + ".join(
                f"{fmt_number(coefficient)}*{left}*{right}" for left, right, coefficient in terms
            )
            or "0"
        )
        from quantsmind.quantum.core.objective import Objective, ObjectiveSense

        return Objective(
            self.name,
            ObjectiveSense.MINIMIZE,
            expression=expression,
            metadata={"data_kind": self.kind},
        )


def objective_from_dict(data: dict[str, Any]) -> DataObjective:
    """Rebuild any supported Data objective from :meth:`to_dict` output."""
    kind = str(data.get("kind", ""))
    if kind == "feature_utility":
        return FeatureUtilityObjective(
            name=str(data["name"]),
            description=str(data.get("description", "")),
            utilities={name: float(v) for name, v in data.get("utilities", {}).items()},
        )
    if kind == "selection_cost":
        return SelectionCostObjective(
            name=str(data["name"]),
            description=str(data.get("description", "")),
            costs={name: float(v) for name, v in data.get("costs", {}).items()},
        )
    if kind == "feature_selection":
        return FeatureSelectionObjective(
            name=str(data["name"]),
            description=str(data.get("description", "")),
            utilities={name: float(v) for name, v in data.get("utilities", {}).items()},
            costs={name: float(v) for name, v in data.get("costs", {}).items()},
            penalty=float(data.get("penalty", 1.0)),
        )
    if kind == "clustering_distance":
        return ClusteringDistanceObjective(
            name=str(data["name"]),
            description=str(data.get("description", "")),
        )
    raise DataValidationError(f"unknown data objective kind {kind!r}")


def _linear_objective(
    coefficients: list[float],
    *,
    maximum: bool,
    label: str,
) -> Objective:
    from quantsmind.quantum.core.objective import Objective, ObjectiveSense

    expression = (
        " + ".join(
            f"{fmt_number(coefficient)}*{variable_name(index)}"
            for index, coefficient in enumerate(coefficients)
            if coefficient != 0.0
        )
        or "0"
    )
    return Objective(
        label,
        ObjectiveSense.MAXIMIZE if maximum else ObjectiveSense.MINIMIZE,
        expression=expression,
        metadata={"data_kind": label},
    )
